export const defaultStyles = {
  primary: {
    textDecoration: 'transparent',
    fontSize: '19px',
    maxWidth: '100px',
    width: '100%',
    margin: '0 auto',
    padding: '5px',
    border: '1px solid red',
    color: '#fff',
    background: 'rgb(255, 255, 255)',
    borderRadius: '5px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  secondary: {
    textDecoration: 'transparent',
    fontSize: '19px',
    maxWidth: '100px',
    width: '100%',
    margin: '0 auto',
    padding: '5px',
    border: '1px solid red',
    color: '#fff',
    background: 'rgb(255, 255, 255)',
    borderRadius: '5px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  }
};